---
- name: Reload systemd
  command: systemctl daemon-reload
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

- name: Restart ambari-agent
  service: name=ambari-agent state=restarted