---

- name: Copy arcadia enterprise to target server
  template: src={{ arcadia_config.archive_file }} dest=/tmp/

- name: Extract archive file to ambari service destination
  template: tar -zxf /tmp/{{ arcadia_config.archive_file }} -C {{ arcadia_config.archive_dest }}